# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20160830_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ID',
            new_name='iden',
        ),
    ]
