# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='frontId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='frontId'),
        ),
    ]
